// Code generated by MockGen. DO NOT EDIT.
// Source: project.go

// Package project is a generated GoMock package.
package project

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	feature "github.com/imcclaskey/d3/internal/core/feature"
	session "github.com/imcclaskey/d3/internal/core/session"
)

// MockStorageService is a mock of StorageService interface.
type MockStorageService struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceMockRecorder
}

// MockStorageServiceMockRecorder is the mock recorder for MockStorageService.
type MockStorageServiceMockRecorder struct {
	mock *MockStorageService
}

// NewMockStorageService creates a new mock instance.
func NewMockStorageService(ctrl *gomock.Controller) *MockStorageService {
	mock := &MockStorageService{ctrl: ctrl}
	mock.recorder = &MockStorageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageService) EXPECT() *MockStorageServiceMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStorageService) Load() (*session.SessionState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*session.SessionState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStorageServiceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStorageService)(nil).Load))
}

// Save mocks base method.
func (m *MockStorageService) Save(arg0 *session.SessionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorageServiceMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorageService)(nil).Save), arg0)
}

// MockFeatureServicer is a mock of FeatureServicer interface.
type MockFeatureServicer struct {
	ctrl     *gomock.Controller
	recorder *MockFeatureServicerMockRecorder
}

// MockFeatureServicerMockRecorder is the mock recorder for MockFeatureServicer.
type MockFeatureServicerMockRecorder struct {
	mock *MockFeatureServicer
}

// NewMockFeatureServicer creates a new mock instance.
func NewMockFeatureServicer(ctrl *gomock.Controller) *MockFeatureServicer {
	mock := &MockFeatureServicer{ctrl: ctrl}
	mock.recorder = &MockFeatureServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeatureServicer) EXPECT() *MockFeatureServicerMockRecorder {
	return m.recorder
}

// CreateFeature mocks base method.
func (m *MockFeatureServicer) CreateFeature(ctx context.Context, featureName string) (*feature.FeatureInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeature", ctx, featureName)
	ret0, _ := ret[0].(*feature.FeatureInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeature indicates an expected call of CreateFeature.
func (mr *MockFeatureServicerMockRecorder) CreateFeature(ctx, featureName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeature", reflect.TypeOf((*MockFeatureServicer)(nil).CreateFeature), ctx, featureName)
}

// MockRulesServicer is a mock of RulesServicer interface.
type MockRulesServicer struct {
	ctrl     *gomock.Controller
	recorder *MockRulesServicerMockRecorder
}

// MockRulesServicerMockRecorder is the mock recorder for MockRulesServicer.
type MockRulesServicerMockRecorder struct {
	mock *MockRulesServicer
}

// NewMockRulesServicer creates a new mock instance.
func NewMockRulesServicer(ctrl *gomock.Controller) *MockRulesServicer {
	mock := &MockRulesServicer{ctrl: ctrl}
	mock.recorder = &MockRulesServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRulesServicer) EXPECT() *MockRulesServicerMockRecorder {
	return m.recorder
}

// RefreshRules mocks base method.
func (m *MockRulesServicer) RefreshRules(feature, phaseStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshRules", feature, phaseStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshRules indicates an expected call of RefreshRules.
func (mr *MockRulesServicerMockRecorder) RefreshRules(feature, phaseStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshRules", reflect.TypeOf((*MockRulesServicer)(nil).RefreshRules), feature, phaseStr)
}

// MockPhaseServicer is a mock of PhaseServicer interface.
type MockPhaseServicer struct {
	ctrl     *gomock.Controller
	recorder *MockPhaseServicerMockRecorder
}

// MockPhaseServicerMockRecorder is the mock recorder for MockPhaseServicer.
type MockPhaseServicerMockRecorder struct {
	mock *MockPhaseServicer
}

// NewMockPhaseServicer creates a new mock instance.
func NewMockPhaseServicer(ctrl *gomock.Controller) *MockPhaseServicer {
	mock := &MockPhaseServicer{ctrl: ctrl}
	mock.recorder = &MockPhaseServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPhaseServicer) EXPECT() *MockPhaseServicerMockRecorder {
	return m.recorder
}

// EnsurePhaseFiles mocks base method.
func (m *MockPhaseServicer) EnsurePhaseFiles(featureDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePhaseFiles", featureDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsurePhaseFiles indicates an expected call of EnsurePhaseFiles.
func (mr *MockPhaseServicerMockRecorder) EnsurePhaseFiles(featureDir interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePhaseFiles", reflect.TypeOf((*MockPhaseServicer)(nil).EnsurePhaseFiles), featureDir)
}

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// ChangePhase mocks base method.
func (m *MockProjectService) ChangePhase(ctx context.Context, targetPhase session.Phase) (*Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePhase", ctx, targetPhase)
	ret0, _ := ret[0].(*Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePhase indicates an expected call of ChangePhase.
func (mr *MockProjectServiceMockRecorder) ChangePhase(ctx, targetPhase interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePhase", reflect.TypeOf((*MockProjectService)(nil).ChangePhase), ctx, targetPhase)
}

// CreateFeature mocks base method.
func (m *MockProjectService) CreateFeature(ctx context.Context, featureName string) (*Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeature", ctx, featureName)
	ret0, _ := ret[0].(*Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeature indicates an expected call of CreateFeature.
func (mr *MockProjectServiceMockRecorder) CreateFeature(ctx, featureName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeature", reflect.TypeOf((*MockProjectService)(nil).CreateFeature), ctx, featureName)
}

// Init mocks base method.
func (m *MockProjectService) Init(clean bool) (*Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", clean)
	ret0, _ := ret[0].(*Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockProjectServiceMockRecorder) Init(clean interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockProjectService)(nil).Init), clean)
}

// IsInitialized mocks base method.
func (m *MockProjectService) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockProjectServiceMockRecorder) IsInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockProjectService)(nil).IsInitialized))
}

// RequiresInitialized mocks base method.
func (m *MockProjectService) RequiresInitialized() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresInitialized")
	ret0, _ := ret[0].(error)
	return ret0
}

// RequiresInitialized indicates an expected call of RequiresInitialized.
func (mr *MockProjectServiceMockRecorder) RequiresInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresInitialized", reflect.TypeOf((*MockProjectService)(nil).RequiresInitialized))
}
