// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/imcclaskey/d3/internal/project (interfaces: ProjectService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	session "github.com/imcclaskey/d3/internal/core/session"
	project "github.com/imcclaskey/d3/internal/project"
)

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// ChangePhase mocks base method.
func (m *MockProjectService) ChangePhase(arg0 context.Context, arg1 session.Phase) (*project.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePhase", arg0, arg1)
	ret0, _ := ret[0].(*project.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePhase indicates an expected call of ChangePhase.
func (mr *MockProjectServiceMockRecorder) ChangePhase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePhase", reflect.TypeOf((*MockProjectService)(nil).ChangePhase), arg0, arg1)
}

// CreateFeature mocks base method.
func (m *MockProjectService) CreateFeature(arg0 context.Context, arg1 string) (*project.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFeature", arg0, arg1)
	ret0, _ := ret[0].(*project.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFeature indicates an expected call of CreateFeature.
func (mr *MockProjectServiceMockRecorder) CreateFeature(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFeature", reflect.TypeOf((*MockProjectService)(nil).CreateFeature), arg0, arg1)
}

// Init mocks base method.
func (m *MockProjectService) Init(arg0 bool) (*project.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", arg0)
	ret0, _ := ret[0].(*project.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Init indicates an expected call of Init.
func (mr *MockProjectServiceMockRecorder) Init(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockProjectService)(nil).Init), arg0)
}

// IsInitialized mocks base method.
func (m *MockProjectService) IsInitialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInitialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInitialized indicates an expected call of IsInitialized.
func (mr *MockProjectServiceMockRecorder) IsInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInitialized", reflect.TypeOf((*MockProjectService)(nil).IsInitialized))
}

// RequiresInitialized mocks base method.
func (m *MockProjectService) RequiresInitialized() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequiresInitialized")
	ret0, _ := ret[0].(error)
	return ret0
}

// RequiresInitialized indicates an expected call of RequiresInitialized.
func (mr *MockProjectServiceMockRecorder) RequiresInitialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequiresInitialized", reflect.TypeOf((*MockProjectService)(nil).RequiresInitialized))
}
