name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: make test

      - name: Generate coverage summary
        run: |
          echo "# Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          make coverage-summary 2>&1 | tee >(cat >> $GITHUB_STEP_SUMMARY)
        id: coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 7

      - name: Build
        run: make build 